core/urls.py
from django.urls import path, re_path
from core.views import main
from core.views import pedido
from core.views import reporte
from core.views import thedocs
from core.views import thejson
from core.views import thepdf

urlpatterns = [
    # Main
    path( '', main.index, name = 'index' ),
    path( 'login/', main.the_login, name = 'the_login' ),
    path( 'logout/', main.the_logout, name = 'the_logout' ),

    # Pedidos
    path( 'pedido/', pedido.pedido, name = 'pedido' ),
    path( 'pedido/lista/mozo/', pedido.pedido_lista_mozo, name = 'pedido_lista_mozo' ),
    path( 'pedido/lista/cocina/', pedido.pedido_lista_cocina, name = 'pedido_lista_cocina' ),
    path( 'pedido/lista/recepcion/', pedido.pedido_lista_recepcion, name = 'pedido_lista_recepcion' ),
    path( 'pedido/crear/', pedido.pedido_crear, name = 'pedido_crear' ), 
    path( 'pedido/quitar/', pedido.pedido_quitar, name = 'pedido_quitar' ), 
    path( 'pedido/atender/', pedido.pedido_atender, name = 'pedido_atender' ), 
    path( 'pedido/imprimir/', pedido.pedido_imprimir, name = 'pedido_imprimir' ),
    re_path( r'^pedido/imprimir/consumo/(?P<id>.*)$', thepdf.pedido_imprimir_consumo, name = 'pedido_imprimir_consumo' ), 
    re_path( r'^pedido/imprimir/comanda/(?P<id>.*)$', thepdf.pedido_imprimir_comanda, name = 'pedido_imprimir_comanda' ), 
    re_path( r'^pedido/imprimir/boleta/(?P<id>.*)$', thepdf.pedido_imprimir_boleta, name = 'pedido_imprimir_boleta' ), 
    re_path( r'^pedido/imprimir/factura/(?P<id>.*)$', thepdf.pedido_imprimir_factura, name = 'pedido_imprimir_factura' ),

    # Reportes
    path( 'reporte/pedido/fecha/', reporte.reporte_pedido_fecha, name = 'reporte_pedido_fecha' ), 
    path( 'reporte/pedido/habitacion/', reporte.reporte_pedido_habitacion, name = 'reporte_pedido_habitacion' ), 
    path( 'reporte/pedido/mozo/', reporte.reporte_pedido_mozo, name = 'reporte_pedido_mozo' ), 
    path( 'reporte/documento/comanda/', reporte.reporte_documento_comanda, name = 'reporte_documento_comanda' ),
    path( 'reporte/documento/consumo/', reporte.reporte_documento_consumo, name = 'reporte_documento_consumo' ),
    path( 'reporte/documento/boleta/', reporte.reporte_documento_boleta, name = 'reporte_documento_boleta' ), 
    path( 'reporte/documento/factura/', reporte.reporte_documento_factura, name = 'reporte_documento_factura' ), 
    path( 'reporte/mozo/masvendido/', reporte.mas_vendido_mozo, name = 'mas_vendido_mozo' ), 
    path( 'reporte/plato/ranking/', reporte.ranking_platos, name = 'ranking_platos' ), 

    #Completo
    path( 'pedido/lista/completo/mozo/', pedido.pedido_lista_completo_mozo, name = 'pedido_lista_completo_mozo' ),

    # Varios.
    path( 'blog/', main.blog, name = 'blog' ),
    path( 'chat/', main.chat, name = 'chat' ),
    path( 'carta/', main.carta, name = 'carta' ),
    path( 'clientes/', main.clientes, name = 'clientes' ),
    path( 'clientes/agregar/', main.cliente_agregar, name = 'cliente_agregar' ),
    path( 'checkout/', main.checkout, name = 'checkout' ),

    # JSON.
    re_path( r'^json/cliente/(?P<q>.*)/$', thejson.json_clientes_local, name = 'json_clientes_local' ),
    re_path( r'^json/plato/(?P<q>.*)/$', thejson.json_platos_local, name = 'json_platos_local' ),
    re_path( r'^json/pedido/habitacion/(?P<id>.*)/$', thejson.pedido_lista_habitacion, name = 'pedido_lista_habitacion' ),
    re_path( r'^json/pedido/externos/$', thejson.pedido_lista_externos, name = 'pedido_lista_externos' ),
    re_path( r'^json/consumo/(?P<id>.*)/$', thedocs.tiene_consumo, name = 'tiene_consumo' ),
    re_path( r'^json/comanda/(?P<id>.*)/$', thedocs.tiene_comanda, name = 'tiene_comanda' ),
    re_path( r'^json/boleta/(?P<id>.*)/$', thedocs.tiene_boleta, name = 'tiene_boleta' ),
    re_path( r'^json/factura/(?P<id>.*)/$', thedocs.tiene_factura, name = 'tiene_factura' ),
    re_path( r'^json/pagar/(?P<id>.*)/$', pedido.json_pagar, name = 'json_pagar' ),
]

ninos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path( 'admin/', admin.site.urls ),
    path( '', include('core.urls') ),
]

if settings.DEBUG:
    from django.conf.urls import url
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

core/models.py
from django.db import models
from django.contrib.auth.models import User


#Ubicacion
class Local(models.Model):
    nombre = models.CharField(max_length = 20)
    direccion = models.CharField(max_length = 100)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Locales"

class Habitacion(models.Model):
    nombre = models.CharField(max_length = 50)
    pertenece_a = models.ForeignKey(Local, on_delete=models.PROTECT)

    def __str__(self):
        return "%s: %s" % (self.pertenece_a, self.nombre)

    class Meta:
        verbose_name_plural = "Habitaciones"

class Punto(models.Model):
    nombre = models.CharField(max_length = 20)
    pertenece_a  = models.ForeignKey(Local, on_delete=models.PROTECT)

    def __str__(self):
        return "%s: %s" % (self.pertenece_a, self.nombre)

class Cliente(models.Model):
    nombres = models.CharField(max_length = 100)
    apellidos = models.CharField(max_length = 100)
    hospedado_en = models.ForeignKey(Habitacion, on_delete=models.PROTECT)
    pais = models.CharField(max_length = 100)
    documento = models.CharField(max_length = 50)
    activo = models.BooleanField(default = True)
    ingreso_pais = models.DateField()
    ingreso = models.DateField()
    salida = models.DateField(null = True, blank = True)

    def __str__(self):
        return "%s %s" % (self.nombres, self.apellidos)

    def my_habitacion(self):
        return "%s: %s" % (self.hospedado_en.pertenece_a, self.hospedado_en.nombre)
    my_habitacion.short_description = 'Donde está hospedado'

    habitacion = property(my_habitacion)

# Cocina.
class Tipo(models.Model):
    RECIBOS = (
        ('C', 'Comanda'),
        ('D', 'Detalle de Consumo'),
    )
    nombre = models.CharField(max_length = 100)
    recibo = models.CharField(max_length = 1, choices = RECIBOS, default = 'D')

    def __str__(self):
        return self.nombre

class PlatoManager(models.Manager):
    def get_by_natural_key(self, nombre, precio):
        return self.get(nombre = nombre, precio = precio)

class Plato(models.Model):
    objects = PlatoManager()
    nombre = models.CharField(max_length = 255)
    tipo = models.ForeignKey(Tipo, on_delete=models.PROTECT)
    de_venta_en = models.ManyToManyField(Punto)
    foto = models.FileField(upload_to = 'fotos', default = 'default.jpg')
    activo = models.BooleanField(default = True)

    def __str__(self):
        return self.nombre

class PrecioPlato(models.Model):
    precio_de = models.ForeignKey(Plato, on_delete=models.PROTECT)
    precio = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)
    anio = models.IntegerField(verbose_name = 'Año')

    class Meta:
        verbose_name = "Precio"
        verbose_name_plural = "Precios"

    def __str__(self):
        return str(self.precio)

# Pedidos
class Pedido(models.Model):
    ESTADOS = (
        ('R', 'Recibido'),
        ('A', 'Atendido'),
        ('I', 'Impreso'),
        ('P', 'Pagado'),
    )
    hecho_por = models.ForeignKey(User, on_delete=models.PROTECT)
    para = models.ForeignKey(Cliente, on_delete=models.PROTECT)
    cuando = models.DateTimeField()
    estado = models.CharField(max_length = 1, choices = ESTADOS, default = 'R')
    punto = models.ForeignKey(Punto, on_delete=models.PROTECT)
    notas = models.TextField()

class PedidoDetalle(models.Model):
    pertenece_al_pedido = models.ForeignKey(Pedido, on_delete=models.PROTECT)
    plato = models.ForeignKey(Plato, on_delete=models.PROTECT)
    cantidad = models.IntegerField()

class Visitante(models.Model):
    nombres = models.CharField(max_length = 200)
    local = models.ForeignKey(Local, on_delete=models.PROTECT)
    pedido = models.OneToOneField(Pedido, on_delete=models.PROTECT)

    def __str__(self):
        return self.nombres

class Bitacora(models.Model):
    hecho_por = models.ForeignKey(User, on_delete=models.PROTECT)
    local = models.ForeignKey(Local, on_delete=models.PROTECT)
    cuando = models.DateTimeField()
    mensaje = models.TextField()

class Chat(models.Model):
    hecho_por = models.ForeignKey(User, on_delete=models.PROTECT)
    mensaje = models.TextField()
    cuando = models.DateTimeField()

# Documentos
class Comanda(models.Model):
    numero = models.IntegerField()
    fecha = models.DateField(auto_now_add = True)
    local = models.ForeignKey(Local, on_delete=models.PROTECT)
    pedido = models.OneToOneField(Pedido, on_delete=models.PROTECT)
    total = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)

    def save(self):
        if self.numero == None:
            total = Comanda.objects.filter(local = self.local).count()
            self.numero = total + 1
        super(Comanda, self).save()

class ComandaDetalle(models.Model):
    pertenece_a_comanda = models.ForeignKey(Comanda, on_delete=models.PROTECT)
    plato = models.ForeignKey(Plato, on_delete=models.PROTECT)
    cantidad = models.IntegerField()
    unitario = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)
    subtotal = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)

class Consumo(models.Model):
    numero = models.IntegerField()
    fecha = models.DateField(auto_now_add = True)
    local = models.ForeignKey(Local, on_delete=models.PROTECT)
    pedido = models.OneToOneField(Pedido, on_delete=models.PROTECT)
    total = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)

    def save(self):
        if self.numero == None:
            total = Consumo.objects.filter(local = self.local).count()
            self.numero = total + 1
        super(Consumo, self).save()

class ConsumoDetalle(models.Model):
    pertenece_a_consumo = models.ForeignKey(Consumo, on_delete=models.PROTECT)
    plato = models.ForeignKey(Plato, on_delete=models.PROTECT)
    cantidad = models.IntegerField()
    unitario = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)
    subtotal = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)

class Boleta(models.Model):
    numero = models.IntegerField()
    fecha = models.DateField(auto_now_add = True)
    local = models.ForeignKey(Local, on_delete=models.PROTECT)
    pedido = models.OneToOneField(Pedido, on_delete=models.PROTECT)
    total = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)

class BoletaDetalle(models.Model):
    pertenece_a_boleta = models.ForeignKey(Boleta, on_delete=models.PROTECT)
    plato = models.ForeignKey(Plato, on_delete=models.PROTECT)
    cantidad = models.IntegerField()
    unitario = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)
    subtotal = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)

class Factura(models.Model):
    numero = models.IntegerField()
    fecha = models.DateField(auto_now_add = True)
    local = models.ForeignKey(Local, on_delete=models.PROTECT)
    pedido = models.OneToOneField(Pedido, on_delete=models.PROTECT)
    total = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)

class FacturaDetalle(models.Model):
    pertenece_a_factura = models.ForeignKey(Factura, on_delete=models.PROTECT)
    plato = models.ForeignKey(Plato, on_delete=models.PROTECT)
    cantidad = models.IntegerField()
    unitario = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)
    subtotal = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)

templates/base.html
<!doctype html>
<html>
  <head>
    <title>{% block title %}Cafetín{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <link rel="stylesheet" media="screen" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/jquery.ui.min.css">
    <link rel="stylesheet" href="/static/css/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/animate.min.css">
    <link rel="stylesheet" media="screen" href="/static/css/cafetin.css">
    {% block css %}{% endblock %}
  </head>
  <body>
    <div id="wrap">
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" data-toggle="collapse" data-target=".navbar-ex1-collapse" class="navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="/" class="navbar-brand">Niños Hotel Cafetín</a>
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            {% include 'menu.html' %}
          </ul>
        </div>
      </nav>
      <div class="container">
        {% if messages %}
          {% for message in messages %}
          <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} animated bounceIn">
            <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
            <p>{{ message }}</p>
          </div>
          {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
      </div>      
    </div>
    <footer id="footer">
      <div class="container">
        <p class="text-muted credit text-right">
          {% if user.is_authenticated %}
          Estás como <strong>{{ user.first_name }} ({{ user.username }})</strong> en <strong>{{ request.session.local }}</strong>
          {% else %}
          Cafetín &copy; 2013
          {% endif %}
        </p>
      </div>
    </footer>
    <script src="/static/js/vendor/jquery.min.js"></script>
    <script src="/static/js/vendor/jquery.ui.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/js/actions/vars.js"></script>
    <script>
      document.write('<sc'+'ript src="' + cafetin.ip + ':3000/socket.io/socket.io.js"></scri'+'pt>');
    </script>    
    <script>
      io = io.connect(cafetin.ip, {'port': 3000});
      io.emit('room', {'room': '{{ request.session.local }}'});
      cafetin.username = '{{ user.username }}';
    </script>
    {% block js %}{% endblock %}
  </body>
</html>

templates/carta.html
{% extends 'base.html' %}
{% block content %}
<h1>Carta</h1>
<div class="form">
  <div class="form-group"><input type="search" class="form-control" id="filter" placeholder="Escribe un nombre para filtrar"></div>
</div>
<table class="table table-striped" id="pedido-carta">
  <thead>
    <tr>
      <th>Plato</th>
      <th>Tipo</th>
      <th>Precio</th>
      <th>Foto</th>
    </tr>
  </thead>
  <tbody>
    {% for plato in platos %}
    <tr>
      <td><span>{{ plato.nombre }}</span></td>
      <td>{{ plato.tipo }}</td>
      <td class="text-right">{{ plato.theprecio }}</td>
      <td><a href="/media/{{ plato.foto }}" title="{{ plato.nombre }}" class="colorbox">Ver foto</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>  
{% csrf_token %}
{% endblock %}
{% block js %}
<script src="/media/js/vendor/jquery.liveFilter.js"></script>
<script src="/media/js/vendor/jquery.colorbox-min.js"></script>
<script src="/media/js/actions/carta.js"></script>
{% endblock %}
{% block css %}
<link rel="stylesheet" href="/media/css/colorbox.css">
{% endblock %}

templates/cliente-agregar.html
{% extends 'base.html' %}
{% block content %}
<h1>Nuevo cliente en {{ request.session.local }}</h1>

<form action="" id="the-form" role="form" method="post">
  <div class="form-group">
    <label for="nombres">Nombres:</label>
    <input type="text" class="form-control" id="nombres" name="nombres" maxlength="100" required autofocus>
  </div>
  <div class="form-group">
    <label for="apellidos">Apellidos:</label>
    <input type="text" class="form-control" id="apellidos" name="apellidos" maxlength="100" required>
  </div>
  <div class="form-group">
    <label for="hospedado_en">Hospedado en:</label>
    <select name="hospedado_en" id="hospedado_en" class="form-control" required="">
      <option value="">Escoge una habitación</option>
      {% for habitacion in habitaciones %}
      <option value="{{ habitacion.id}}">{{ habitacion.nombre }}</option>
      {% endfor %}
    </select>
  </div>
  <div class="form-group">
    <label for="pais">País:</label>
    <input type="text" class="form-control" id="pais" name="pais" maxlength="50" required>
  </div>
  <div class="form-group">
    <label for="documento">Documento:</label>
    <input type="text" class="form-control" id="documento" name="documento" maxlength="50" required autocomplete="off">
  </div>
  <div class="form-group">
    <label for="ingreso_pais">Ingreso al país:</label>
    <input type="text" class="form-control datepicker" id="ingreso_pais" name="ingreso_pais" maxlength="50" required>
  </div>
  <div class="form-group">
    <label for="ingreso">Ingreso al hotel:</label>
    <input type="text" class="form-control datepicker" id="ingreso" name="ingreso" maxlength="50" required>
  </div>
  <div class="form-group">
    <label for="salida">Salida del hotel:</label>
    <input type="text" class="form-control datepicker" id="salida" name="salida" maxlength="50">
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox" checked name="activo"> Este cliente está activo, es decir, hospedado.
    </label>
  </div>
  <button class="btn btn-primary" type="submit">Guardar cliente</button>
  <a href="{% url 'clientes' %}" class="btn btn-default">Cancelar</a>
  {% csrf_token %}
</form>
{% endblock %}
{% block js %}
<script src="/media/js/actions/cliente-agregar.js"></script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Bienvenido</h1>
<p>Hola <strong>{{ user.first_name }}</strong> acabas de ingresar a <strong>{{ request.session.local }}</strong></p>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Iniciar Sesión</h1>
<form role="form" action="{% url 'the_login' %}" method="post" class="form-horizontal">
  <div class="form-group">
    <label for="username" class="col-lg-2 control-label">Usuario</label>
    <div class="col-lg-3">
      <select id="username" name="username" class="form-control" required>
        <option value="">Escoge un usuario</option>
        {% for user in usuarios %}
        {% if user.id != 1%}
        <option value="{{user.username}}">{{user.username}}</option>
        {% endif %}
        {% endfor %}
      </select>
    </div>
  </div>
  <div class="form-group">
    <label for="password" class="col-lg-2 control-label">Password</label>
    <div class="col-lg-3">
      <input id="password" name="password" type="password" class="form-control" required>
    </div>
  </div>
  <div class="form-group">
    <label for="local" class="col-lg-2 control-label">Local</label>
    <div class="col-lg-3">
      <select id="local" name="local" class="form-control" required>
        <option value="">Escoge un local</option>
        {% for local in locales %}
        <option value="{{local.pk}}">{{local.nombre}}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-3">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary btn-block">Ingresar</button>
    </div>
  </div>
</form>
{% endblock %}

templates/pedido-lista-cocina.html
{% extends 'base.html' %}
{% block content %}
<h1>Lista de pedidos</h1>
<ul class="nav nav-tabs">
{% for punto in puntos %}
<li{% if forloop.first %} class="active"{% endif %}>
  <a href="#tab-{{ punto.id }}" data-toggle="tab">{{ punto }}</a>
</li>
{% endfor %}
</ul>
<div class="tab-content">
{% for punto in puntos %}
  <div id="tab-{{ punto.id }}" class="tab-pane{% if forloop.first %} active{% endif %}">
    <table class="table table-striped pedido-lista" id="pedido-lista-{{ punto.id }}">
      <thead>
        <tr>
          <th>Cliente</th>
          <th>Pedido</th>
          <th>Comentarios</th>
          <th>Mozo</th>
          <th>Fecha</th>
          <th>Estado</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        {% for pedido in pedidos %}
        {% ifequal pedido.punto punto %}
          <tr id="row-{{ pedido.id }}">
            {% if pedido.visitante %}
            <td><strong>Foraneo:</strong> {{ pedido.visitante }}</td>
            {% else %}
            <td>{{ pedido.para }}</td>
            {% endif %}
            <td>
              <ul class="list-unstyled">
                {% for detalle in pedido.pedidodetalle_set.all %}
                <li>{{ detalle.cantidad }} x {{ detalle.plato }}</li>
                {% endfor %}
              </ul>
            </td>
            <td>{{ pedido.notas }}</td>
            <td>{{ pedido.first_name }}</td>
            <td class="timeago" title="{{ pedido.cuando |date:"c"}}">{{ pedido.cuando |date:"D d M Y"}}</td>
            <td>
              {% ifequal pedido.estado 'R' %}
              <span class="btn btn-sm btn-danger">Recibido</span>
              {% endifequal %}
              {% ifequal pedido.estado 'A' %}
              <span class="btn btn-sm btn-warning">Atendido</span>
              {% endifequal %}
              {% ifequal pedido.estado 'I' %}
              <span class="btn btn-sm btn-info">Impreso</span>
              {% endifequal %}
              {% ifequal pedido.estado 'P' %}
              <span class="btn btn-sm btn-success">Pagado</span>
              {% endifequal %}
            </td>
            </td>
            <td>
              {% ifequal pedido.estado 'R' %}
              <button class="btn btn-sm btn-warning attend" data-id={{ pedido.id }}><i class="icon icon-check"></i></button>
              <button class="btn btn-sm btn-info print" data-id="{{ pedido.id }}" data-comanda="{{ pedido.tiene_comanda }}" 
              data-consumo="{{ pedido.tiene_consumo }}" 
              {% if pedido.visitante%}
              data-foraneo="true"
              {% else %}
              data-foraneo="false"
              {% endif %}
               style="display: none;"><i class="icon icon-print"></i></button>
              {% endifequal %}
              {% ifequal pedido.estado 'A' %}
              <button class="btn btn-sm btn-info print" data-id="{{ pedido.id }}" data-comanda="{{ pedido.tiene_comanda }}" 
              data-consumo="{{ pedido.tiene_consumo }}" 
              {% if pedido.visitante%}
              data-foraneo="true"
              {% else %}
              data-foraneo="false"
              {% endif %}
              ><i class="icon icon-print"></i></button>
              {% endifequal %}
              {% ifequal pedido.estado 'I' %}
              <button class="btn btn-sm btn-info print" data-id="{{ pedido.id }}" data-comanda="{{ pedido.tiene_comanda }}" 
              data-consumo="{{ pedido.tiene_consumo }}" 
              {% if pedido.visitante%}
              data-foraneo="true"
              {% else %}
              data-foraneo="false"
              {% endif %}
              ><i class="icon icon-print"></i></button>
              {% endifequal %}
              {% ifequal pedido.estado 'P' %}
              <button class="btn btn-sm btn-info print" data-id="{{ pedido.id }}" data-comanda="{{ pedido.tiene_comanda }}" 
              data-consumo="{{ pedido.tiene_consumo }}" 
              {% if pedido.visitante%}
              data-foraneo="true"
              {% else %}
              data-foraneo="false"
              {% endif %}
              ><i class="icon icon-print"></i></button>
              {% endifequal %}
            </td>
          </tr>
        {% endifequal %}
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endfor %}
</div>

<div class="modal fade" id="theModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Impresión</h4>
      </div>
      <div class="modal-body">
        <button class="btn btn-primary comanda" data-what="comanda">Imprimir Comanda</button>
        <button class="btn btn-primary consumo" data-what="consumo">Imprimir Detalle de Consumo</button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="printModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Impresión</h4>
      </div>
      <div class="modal-body">
        <iframe src="" style="zoom:0.60" width="99.6%" height="600" frameborder="0"></iframe>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

{% csrf_token %}
{% endblock %}
{% block js %}
<script src="/media/js/vendor/jquery.timeago.js"></script>
<script src="/media/js/actions/pedido-lista-cocina.js"></script>
{% endblock %}