core/urls.py
from django.urls import path, re_path
from core.views import main
from core.views import pedido
from core.views import reporte
from core.views import thedocs
from core.views import thejson
from core.views import thepdf

urlpatterns = [
    # Main
    path( '', main.index, name = 'index' ),
    path( 'login/', main.the_login, name = 'the_login' ),
    path( 'logout/', main.the_logout, name = 'the_logout' ),

    # Pedidos
    path( 'pedido/', pedido.pedido, name = 'pedido' ),
    path( 'pedido/lista/mozo/', pedido.pedido_lista_mozo, name = 'pedido_lista_mozo' ),
    path( 'pedido/lista/cocina/', pedido.pedido_lista_cocina, name = 'pedido_lista_cocina' ),
    path( 'pedido/lista/recepcion/', pedido.pedido_lista_recepcion, name = 'pedido_lista_recepcion' ),
    path( 'pedido/crear/', pedido.pedido_crear, name = 'pedido_crear' ), 
    path( 'pedido/quitar/', pedido.pedido_quitar, name = 'pedido_quitar' ), 
    path( 'pedido/atender/', pedido.pedido_atender, name = 'pedido_atender' ), 
    path( 'pedido/imprimir/', pedido.pedido_imprimir, name = 'pedido_imprimir' ),
    re_path( r'^pedido/imprimir/consumo/(?P<id>.*)$', thepdf.pedido_imprimir_consumo, name = 'pedido_imprimir_consumo' ), 
    re_path( r'^pedido/imprimir/comanda/(?P<id>.*)$', thepdf.pedido_imprimir_comanda, name = 'pedido_imprimir_comanda' ), 
    re_path( r'^pedido/imprimir/boleta/(?P<id>.*)$', thepdf.pedido_imprimir_boleta, name = 'pedido_imprimir_boleta' ), 
    re_path( r'^pedido/imprimir/factura/(?P<id>.*)$', thepdf.pedido_imprimir_factura, name = 'pedido_imprimir_factura' ),

    # Reportes
    path( 'reporte/pedido/fecha/', reporte.reporte_pedido_fecha, name = 'reporte_pedido_fecha' ), 
    path( 'reporte/pedido/habitacion/', reporte.reporte_pedido_habitacion, name = 'reporte_pedido_habitacion' ), 
    path( 'reporte/pedido/mozo/', reporte.reporte_pedido_mozo, name = 'reporte_pedido_mozo' ), 
    path( 'reporte/documento/comanda/', reporte.reporte_documento_comanda, name = 'reporte_documento_comanda' ),
    path( 'reporte/documento/consumo/', reporte.reporte_documento_consumo, name = 'reporte_documento_consumo' ),
    path( 'reporte/documento/boleta/', reporte.reporte_documento_boleta, name = 'reporte_documento_boleta' ), 
    path( 'reporte/documento/factura/', reporte.reporte_documento_factura, name = 'reporte_documento_factura' ), 
    path( 'reporte/mozo/masvendido/', reporte.mas_vendido_mozo, name = 'mas_vendido_mozo' ), 
    path( 'reporte/plato/ranking/', reporte.ranking_platos, name = 'ranking_platos' ), 

    #Completo
    path( 'pedido/lista/completo/mozo/', pedido.pedido_lista_completo_mozo, name = 'pedido_lista_completo_mozo' ),

    # Varios.
    path( 'blog/', main.blog, name = 'blog' ),
    path( 'chat/', main.chat, name = 'chat' ),
    path( 'carta/', main.carta, name = 'carta' ),
    path( 'clientes/', main.clientes, name = 'clientes' ),
    path( 'clientes/agregar/', main.cliente_agregar, name = 'cliente_agregar' ),
    path( 'checkout/', main.checkout, name = 'checkout' ),

    # JSON.
    re_path( r'^json/cliente/(?P<q>.*)/$', thejson.json_clientes_local, name = 'json_clientes_local' ),
    re_path( r'^json/plato/(?P<q>.*)/$', thejson.json_platos_local, name = 'json_platos_local' ),
    re_path( r'^json/pedido/habitacion/(?P<id>.*)/$', thejson.pedido_lista_habitacion, name = 'pedido_lista_habitacion' ),
    re_path( r'^json/pedido/externos/$', thejson.pedido_lista_externos, name = 'pedido_lista_externos' ),
    re_path( r'^json/consumo/(?P<id>.*)/$', thedocs.tiene_consumo, name = 'tiene_consumo' ),
    re_path( r'^json/comanda/(?P<id>.*)/$', thedocs.tiene_comanda, name = 'tiene_comanda' ),
    re_path( r'^json/boleta/(?P<id>.*)/$', thedocs.tiene_boleta, name = 'tiene_boleta' ),
    re_path( r'^json/factura/(?P<id>.*)/$', thedocs.tiene_factura, name = 'tiene_factura' ),
    re_path( r'^json/pagar/(?P<id>.*)/$', pedido.json_pagar, name = 'json_pagar' ),
]

ninos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path( 'admin/', admin.site.urls ),
    path( '', include('core.urls') ),
]

if settings.DEBUG:
    from django.conf.urls import url
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

core/models.py
from django.db import models
from django.contrib.auth.models import User


#Ubicacion
class Local(models.Model):
    nombre = models.CharField(max_length = 20)
    direccion = models.CharField(max_length = 100)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Locales"

class Habitacion(models.Model):
    nombre = models.CharField(max_length = 50)
    pertenece_a = models.ForeignKey(Local, on_delete=models.PROTECT)

    def __str__(self):
        return "%s: %s" % (self.pertenece_a, self.nombre)

    class Meta:
        verbose_name_plural = "Habitaciones"

class Punto(models.Model):
    nombre = models.CharField(max_length = 20)
    pertenece_a  = models.ForeignKey(Local, on_delete=models.PROTECT)

    def __str__(self):
        return "%s: %s" % (self.pertenece_a, self.nombre)

class Cliente(models.Model):
    nombres = models.CharField(max_length = 100)
    apellidos = models.CharField(max_length = 100)
    hospedado_en = models.ForeignKey(Habitacion, on_delete=models.PROTECT)
    pais = models.CharField(max_length = 100)
    documento = models.CharField(max_length = 50)
    activo = models.BooleanField(default = True)
    ingreso_pais = models.DateField()
    ingreso = models.DateField()
    salida = models.DateField(null = True, blank = True)

    def __str__(self):
        return "%s %s" % (self.nombres, self.apellidos)

    def my_habitacion(self):
        return "%s: %s" % (self.hospedado_en.pertenece_a, self.hospedado_en.nombre)
    my_habitacion.short_description = 'Donde está hospedado'

    habitacion = property(my_habitacion)

# Cocina.
class Tipo(models.Model):
    RECIBOS = (
        ('C', 'Comanda'),
        ('D', 'Detalle de Consumo'),
    )
    nombre = models.CharField(max_length = 100)
    recibo = models.CharField(max_length = 1, choices = RECIBOS, default = 'D')

    def __str__(self):
        return self.nombre

class PlatoManager(models.Manager):
    def get_by_natural_key(self, nombre, precio):
        return self.get(nombre = nombre, precio = precio)

class Plato(models.Model):
    objects = PlatoManager()
    nombre = models.CharField(max_length = 255)
    tipo = models.ForeignKey(Tipo, on_delete=models.PROTECT)
    de_venta_en = models.ManyToManyField(Punto)
    foto = models.FileField(upload_to = 'fotos', default = 'default.jpg')
    activo = models.BooleanField(default = True)

    def __str__(self):
        return self.nombre

class PrecioPlato(models.Model):
    precio_de = models.ForeignKey(Plato, on_delete=models.PROTECT)
    precio = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)
    anio = models.IntegerField(verbose_name = 'Año')

    class Meta:
        verbose_name = "Precio"
        verbose_name_plural = "Precios"

    def __str__(self):
        return str(self.precio)

# Pedidos
class Pedido(models.Model):
    ESTADOS = (
        ('R', 'Recibido'),
        ('A', 'Atendido'),
        ('I', 'Impreso'),
        ('P', 'Pagado'),
    )
    hecho_por = models.ForeignKey(User, on_delete=models.PROTECT)
    para = models.ForeignKey(Cliente, on_delete=models.PROTECT)
    cuando = models.DateTimeField()
    estado = models.CharField(max_length = 1, choices = ESTADOS, default = 'R')
    punto = models.ForeignKey(Punto, on_delete=models.PROTECT)
    notas = models.TextField()

class PedidoDetalle(models.Model):
    pertenece_al_pedido = models.ForeignKey(Pedido, on_delete=models.PROTECT)
    plato = models.ForeignKey(Plato, on_delete=models.PROTECT)
    cantidad = models.IntegerField()

class Visitante(models.Model):
    nombres = models.CharField(max_length = 200)
    local = models.ForeignKey(Local, on_delete=models.PROTECT)
    pedido = models.OneToOneField(Pedido, on_delete=models.PROTECT)

    def __str__(self):
        return self.nombres

class Bitacora(models.Model):
    hecho_por = models.ForeignKey(User, on_delete=models.PROTECT)
    local = models.ForeignKey(Local, on_delete=models.PROTECT)
    cuando = models.DateTimeField()
    mensaje = models.TextField()

class Chat(models.Model):
    hecho_por = models.ForeignKey(User, on_delete=models.PROTECT)
    mensaje = models.TextField()
    cuando = models.DateTimeField()

# Documentos
class Comanda(models.Model):
    numero = models.IntegerField()
    fecha = models.DateField(auto_now_add = True)
    local = models.ForeignKey(Local, on_delete=models.PROTECT)
    pedido = models.OneToOneField(Pedido, on_delete=models.PROTECT)
    total = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)

    def save(self):
        if self.numero == None:
            total = Comanda.objects.filter(local = self.local).count()
            self.numero = total + 1
        super(Comanda, self).save()

class ComandaDetalle(models.Model):
    pertenece_a_comanda = models.ForeignKey(Comanda, on_delete=models.PROTECT)
    plato = models.ForeignKey(Plato, on_delete=models.PROTECT)
    cantidad = models.IntegerField()
    unitario = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)
    subtotal = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)

class Consumo(models.Model):
    numero = models.IntegerField()
    fecha = models.DateField(auto_now_add = True)
    local = models.ForeignKey(Local, on_delete=models.PROTECT)
    pedido = models.OneToOneField(Pedido, on_delete=models.PROTECT)
    total = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)

    def save(self):
        if self.numero == None:
            total = Consumo.objects.filter(local = self.local).count()
            self.numero = total + 1
        super(Consumo, self).save()

class ConsumoDetalle(models.Model):
    pertenece_a_consumo = models.ForeignKey(Consumo, on_delete=models.PROTECT)
    plato = models.ForeignKey(Plato, on_delete=models.PROTECT)
    cantidad = models.IntegerField()
    unitario = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)
    subtotal = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)

class Boleta(models.Model):
    numero = models.IntegerField()
    fecha = models.DateField(auto_now_add = True)
    local = models.ForeignKey(Local, on_delete=models.PROTECT)
    pedido = models.OneToOneField(Pedido, on_delete=models.PROTECT)
    total = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)

class BoletaDetalle(models.Model):
    pertenece_a_boleta = models.ForeignKey(Boleta, on_delete=models.PROTECT)
    plato = models.ForeignKey(Plato, on_delete=models.PROTECT)
    cantidad = models.IntegerField()
    unitario = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)
    subtotal = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)

class Factura(models.Model):
    numero = models.IntegerField()
    fecha = models.DateField(auto_now_add = True)
    local = models.ForeignKey(Local, on_delete=models.PROTECT)
    pedido = models.OneToOneField(Pedido, on_delete=models.PROTECT)
    total = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)

class FacturaDetalle(models.Model):
    pertenece_a_factura = models.ForeignKey(Factura, on_delete=models.PROTECT)
    plato = models.ForeignKey(Plato, on_delete=models.PROTECT)
    cantidad = models.IntegerField()
    unitario = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)
    subtotal = models.DecimalField(max_digits = 5, decimal_places = 2, default = 0)

templates/pdf/boleta.html
<html>
<head>
  <style>
    @page {
      size: A5 portrait;
      margin: 5pt;
      @frame fecha_frame {
        -pdf-frame-content: fecha;
        top: 110pt;
        left: 200pt;
      }
      @frame quien_frame {
        -pdf-frame-content: quien;
        top: 130pt;
        left: 70pt;
      }
      @frame content_frame {
        -pdf-frame-content: body_content;
        top: 150pt;
        left: 10pt;
        right: 150pt;
      }
      @frame total_frame {
        -pdf-frame-content: total;
        top: 410pt;
        left: 250pt;
        right: 20pt;
      }

    }

    body {
      font-size: 9pt;
    }

    .smallcell {
      width: 55pt;
    }

    .nomargin {
      padding: 0;
      margin:  0;
    }

    .invisible {
      visibility: hidden;
      color: #FFF;
    }

    .cell {
      padding-right: 5pt;
      padding-left: 5pt;
      padding-top: 0;
      padding-bottom: 0;
    }
  </style>
</head>
<body>
  <!-- Content for Static Frame 'header' -->
  <div id="fecha">
    <p class="nomargin">
      {{ boleta.fecha|date:"d"}}&nbsp;&nbsp;&nbsp;&nbsp;
      {{ boleta.fecha|date:"m"}}&nbsp;&nbsp;&nbsp;&nbsp;
      {{ boleta.fecha|date:"Y"}}
    </p>
  </div>
  <div id="quien">
    <p class="nomargin"> {{ boleta.pedido.visitante | upper }}</p>
  </div>
  <div id="body_content">
    <table cellpadding="5">
        <thead class="hidden">
          <th class="cell invisible smallcell">CANT.</th>
          <th class="cell invisible ">DETALLE DE ALIMENTOS</th>
          <th class="cell invisible smallcell">UNIT.</th>
          <th class="cell invisible smallcell">SUBTOTAL</th>
        </thead>
        <tbody>
        {% for detalle in boleta.boletadetalle_set.all %}
        <tr>
          <td class="smallcell cell">{{ detalle.cantidad }}</td>
          <td class="cell">{{ detalle.plato.nombre | upper }}</td>
          <td class="cell">{{ detalle.unitario }}</td>
          <td class="align-right smallcell cell">{{ detalle.subtotal }}</td>
        </tr>
        {% endfor %}
        <tr>
          <td colspan="3" class="cell">Son {{ boleta.totalnum }} Nuevos Soles</td>
        </tr>
      </tbody>
    </table>

  </div>
  <div id="total">
    <p class="nomargin">{{ boleta.total }}</p>
  </div>
</body>
</html>

templates/pdf/comanda.html
<html>
<head>
  <style>
    @page {
      size: A6 portrait;
      margin: 5pt;
      @frame header_frame {
        -pdf-frame-content: header_content;
        top: 10pt;
        left: 10pt;
        right: 10pt;
      }
      @frame content_frame {
        -pdf-frame-content: body_content;
        top: 70pt;
        left: 10pt;
        right: 10pt;
      }
      @frame footer_frame {
          -pdf-frame-content: footer_content;
          left: 50pt; width: 512pt; top: 772pt; height: 20pt;
      }
    }

    img {zoom 80%}

    .comanda {
      background: #888;
      color: #fff;
      padding: 0pt 10pt;
      padding-top: 5pt;
      font-size: 16pt;
    }

    .align-center {
      text-align: center;
    }

    .align-right {
      text-align: right;
    }

    .smallcell {
      width: 55pt;
    }

    .nro {
      padding-left: 4pt;
    }

    .thenro {
      border: 1px solid black;
      padding-top: 4pt;
      padding-bottom: -4pt;
      font-family: serif;
      font-size: 12pt;
    }

    .nomargin {
      padding: 0;
      margin:  0;
    }

    .firma {
      margin-top: 50pt;
      text-align: center;
      font-size: 9pt;
      border-top: 1pt solid #000;
      padding-top: 3pt;
    }

    #body_content {
      font-size: 8pt;
    }

    .direccion {
      font-size: 7pt;
      margin: 0;
      padding: 0;
    }

    .titulo {
      font-size: 15pt;
      font-weight: bold;
      line-height: 7pt;
      margin: 0;
      padding: 0;
    }
  </style>
</head>
<body>
  <!-- Content for Static Frame 'header' -->
  <div id="header_content">
    <table>
      <tr>
        <td colspan="2">
          <p class="titulo"><img src="logo.jpg">Niños Hotel {{ comanda.local }}</p>
          <p class="direccion">{{ comanda.local.direccion }}</p>
        </td>
      </tr>
      <tr>
        <td><h2 class="comanda align-center">COMANDA</h2></td>
        <td class="nro align-center">
          <p class="thenro">N° {{ comanda.numero }}</p>
        </td>
      </tr>
    </table>
  </div>
  <div id="body_content">
    {% if comanda.pedido.visitante %}
    <p class="nomargin"><strong>Cliente</strong>: {{ comanda.pedido.visitante }}</p>
    {% else %}
    <p class="nomargin"><strong>Cliente</strong>: {{ comanda.pedido.para }} en habitación {{ comanda.pedido.para.hospedado_en }}</p>
    {% endif %}
    <p class="nomargin"><strong>Atendido por</strong>: {{ comanda.pedido.hecho_por.first_name }} {{ comanda.pedido.hecho_por.last_name }}</p>
    <p class="nomargin"><strong>Fecha</strong>: {{ comanda.pedido.cuando }}</p>
    <table border="1" cellpadding="5">
      <thead>
        <tr style="background: #EEE;">
          <th class="smallcell" style="background: #EEE;">CANT.</th>
          <th style="background: #EEE;">PEDIDO</th>
          <th class="smallcell" style="background: #EEE;">UNIT.</th>
          <th class="smallcell" style="background: #EEE;">IMPORTE</th>
        </tr>
      </thead>
      <tbody>
        {% for detalle in comanda.comandadetalle_set.all %}
        <tr>
          <td class="smallcell">{{ detalle.cantidad }}</td>
          <td>{{ detalle.plato.nombre }}</td>
          <td class="align-right">{{ detalle.unitario }}</td>
          <td class="align-right">{{ detalle.subtotal }}</td>
        </tr>
        {% endfor %} 
      </tbody>
      <tfoot>
        <th colspan="3" class="align-right">TOTAL S/.</th>
        <th class="align-right">{{ comanda.total }}</th>
      </tfoot>
    </table>
    <p class="firma">Firma: {{ comanda.pedido.para }}</p>
  </div>


</body>
</html>

templates/pdf/consumo.html
<html>
<head>
  <style>
    @page {
      size: A6 portrait;
      margin: 5pt;
      @frame header_frame {
        -pdf-frame-content: header_content;
        top: 95pt;
        left: 60pt;
        right: 10pt;
      }
      @frame content_frame {
        -pdf-frame-content: body_content;
        top: 110pt;
        left: 10pt;
        right: 25pt;
      }
      @frame total_frame {
        -pdf-frame-content: total;
        top: 302pt;
        left: 245pt;
        right: 25pt;
      }
      @frame fecha_frame {
        -pdf-frame-content: fecha;
        top: 334pt;
        left: 205pt;
        right: 25pt;
      }
    }

    img {zoom 80%}

    .align-center {
      text-align: center;
    }

    .align-right {
      text-align: right;
    }

    .smallcell {
      width: 55pt;
    }

    .nomargin {
      padding: 0;
      margin:  0;
    }

    body {
      font-size: 9pt;
    }

    .invisible {
      visibility: hidden;
      color: #FFF;
    }
  </style>
</head>
<body>
  <!-- Content for Static Frame 'header' -->
  <div id="header_content">
    <p class="nomargin">{{ consumo.pedido.para }} en habitación {{ consumo.pedido.para.hospedado_en }}</p>
  </div>
  <div id="body_content">    
    <table cellpadding="5">
        <thead class="hidden">
          <th class="invisible smallcell">CANT.</th>
          <th class="invisible ">DETALLE DE ALIMENTOS</th>
          <th class="invisible smallcell">UNIT.</th>
          <th class="invisible smallcell">SUBTOTAL</th>
        </thead>
        <tbody>
        {% for detalle in consumo.consumodetalle_set.all %}
        <tr>
          <td class="smallcell">{{ detalle.cantidad }}</td>
          <td>{{ detalle.plato.nombre }}</td>
          <td>{{ detalle.unitario }}</td>
          <td class="align-right smallcell">{{ detalle.subtotal }}</td>
        </tr>
        {% endfor %} 
      </tbody>
    </table>

  </div>
  <div id="total">
    <p class="nomargin">{{ consumo.total }}</p>
  </div>
  <div id="fecha">
    <p class="nomargin">
      {{ consumo.fecha|date:"d"}}&nbsp;&nbsp;&nbsp;&nbsp;
      {{ consumo.fecha|date:"m"}}&nbsp;&nbsp;&nbsp;&nbsp;
      {{ consumo.fecha|date:"Y"}}
    </p>
  </div>


</body>
</html>

templates/pdf/factura.html
<html>
<head>
  <style>
    @page {
      size: A4 landscape;
      margin: 5pt;
      @frame header_frame {
        -pdf-frame-content: header_content;
        top: 180pt;
        left: 230pt;
        right: 80pt;
      }
      @frame content_frame {
        -pdf-frame-content: body_content;
        top: 235pt;
        left: 200pt;
        right: 70pt;
      }
      @frame totalnum_frame {
        -pdf-frame-content: totalnum; 
        top: 460pt;
        left: 250pt;
      }
      @frame cancelado_frame {
        -pdf-frame-content: cancelado;
        top: 485pt;
        left: 470pt;
      }
      @frame total_frame {
        -pdf-frame-content: total;
        top: 455pt;
        left: 720pt;
      }
    }

    .align-right {
      text-align: right;
    }

    .smallcell {
      width: 80pt;
    }

    .nomargin {
      padding: 0;
      margin:  0;
    }

    body {
      font-size: 10pt;
    }

    .invisible {
      visibility: hidden;
      color: #FFF;
    }

    .cell {
      padding-right: 5pt;
      padding-left: 5pt;
      padding-top: 0;
      padding-bottom: 0;
    }
  </style>
</head>
<body>
  <!-- Content for Static Frame 'header' -->
  <div id="header_content">
    <table>
      <tr>
        <td><p class="nomargin"><strong class="invisible">Cliente</strong> {{ factura.pedido.para | upper }}</p></td>
        <td rowspan="2">
          <p class="nomargin align-right">
          {{ factura.fecha|date:"d"}}&nbsp;&nbsp;&nbsp;&nbsp;
          {{ factura.fecha|date:"m"}}&nbsp;&nbsp;&nbsp;&nbsp;
          {{ factura.fecha|date:"Y"}}
          </p>
        </td>
      </tr>
      <tr>
        <td><p class="nomargin"><strong class="invisible">Cliente</strong> {{ factura.pedido.para.documento }}</p></td>
      </tr>
    </table>
    
    

  </div>
  <div id="body_content">
    <table class="factura">
        <thead class="hidden">
          <th class="cell invisible smallcell">CANT.</th>
          <th class="cell invisible ">DETALLE DE ALIMENTOS</th>
          <th class="cell invisible smallcell">SUBTOTAL</th>
        </thead>
        <tbody>
        {% for detalle in factura.facturadetalle_set.all %}
        <tr>
          <td class="cell smallcell">{{ detalle.cantidad }}</td>
          <td class="cell">{{ detalle.plato.nombre }}</td>
          <td class="cell align-right smallcell">S/. {{ detalle.subtotal }}</td>
        </tr>
        {% endfor %}
        <tr>
          <td class="cell smallcell"></td>
          <td class="cell">F.I.P. {{ factura.pedido.para.ingreso_pais }} - País: {{ factura.pedido.para.pais }}</td>
          <td class="cell smallcell"></td>
        </tr>
      </tbody>
    </table>

  </div>
  <div id="totalnum">
    {{ factura.totalnum | capfirst }} Nuevos Soles
  </div>
  <div id="cancelado">
    {{ factura.fecha | date:"d \d\e F \d\e\l Y" }}
  </div>
  <div id="total">
    <p class="nomargin"><strong>S/. {{ factura.total }}</strong></p>
    <p class="nomargin"><strong>S/. 0.00</strong></p>
    <p class="nomargin"><strong>S/. {{ factura.total }}</strong></p>
  </div>
</body>
</html>